### ISSUE TITLE
Add configurable configuration

### ISSUE THREAD

**Issue by ilyasfoo** [moon0326/wp-openapi#1]
It seems currently something is hardcoded here: https://github.com/moon0326/wp-openapi/blob/d0e2e896f88138c3ac84ed32f6ab745a9e799f39/bin/validate.js#L23

I'd like to have a file based configuration, possibly JSON?

Thank you!

**Comment by moon0326** [comment]
Thank you for catching it! Oh well...that's a script I used while developing. I'm going to see if there is a composer package I can use for OpenAPI 3.1.0 spec to replace it with PHP. Otherwise, I'll update it to accept an argument instead.

**Comment by ilyasfoo** [comment]
Sounds good 👍
