### ISSUE TITLE
Not found 404 if WordPress is installed in subdirectory

### ISSUE THREAD

**Issue by beliven-valentino-cossar** [moon0326/wp-openapi#25]
Hi, we are using [Bedrock](https://github.com/roots/bedrock) to install WordPress In` /wp` subdirectory, this is causing 404 error on `wp-json-openapi` endpoint because of using `site_url()` to get the website URL to make the API call. 

Is possible to use `home_url()` instead? Thank you.

**Comment by moon0326** [comment]
@beliven-valentino-cossar [1.0.7](https://downloads.wordpress.org/plugin/wp-openapi.1.0.7.zip) has been released with `home_url()` change.

**Comment by beliven-valentino-cossar** [comment]
Hi @moon0326, [this pull request](#28 ) fixes the issue for me. Can you please test it on your side?

**Comment by moon0326** [comment]
@beliven-valentino-cossar Thanks! It looks like I missed changing the URL in other places. I'll test it out 👍

**Comment by moon0326** [comment]
@beliven-valentino-cossar [1.0.8](https://github.com/moon0326/wp-openapi/releases/download/v1.0.8/wp-openapi.zip) has been released to include your latest changes. Thank you so much 👍

**Comment by beliven-valentino-cossar** [comment]
@moon0326 thank you too!
