### ISSUE TITLE
/wp-json-openapi?namespace=all request goes to WordPress site URL, not install URL

### ISSUE THREAD

**Issue by drewbaker** [moon0326/wp-openapi#44]
So it seems the plugin on load does a request to a URL like this:
https://fuxt-backend.funkhaus.us/wp-json-openapi?namespace=all

This is going to the WordPress site URL, not the location of the installed WordPress.

The reason this is a problem is, with a Headless WordPress setup, the installed location is a different domain than the site URL. So the request will go to the frontend, and give an error. 

For example with this setup:
![Screenshot 2024-10-04 at 3 25 26 PM](https://github.com/user-attachments/assets/96cf237c-ce58-4c9e-b2a5-0496fd3e43e3)

The request goes to `https://fuxt.funkhaus.us/wp-json-openapi?namespace=all` which is a Nuxt app in our case.

So I think it would be good to make that initial request to the WordPress install location, and probably to your own API endpoint rather than the root page level like you have it.

**Comment by moon0326** [comment]
Thank you for opening this issue.

I'll work on it soon.

**Comment by moon0326** [comment]
@drewbaker https://github.com/moon0326/wp-openapi/releases/tag/v1.0.15 has been released to address this issue. The request is now made to the `/wp-json/wp-openapi/v1/schema` endpoint. However, `/wp-json-openapi` still exists for backward compatibility. You can disable it with `wp-openapi-filter-schema-endpoint-permission` filter.

Example code:

```
add_filter('wp-openapi-filter-schema-endpoint-permission', function() {
	if ( get_query_var( 'openapi' ) === 'schema' ) {
		return false;
	}
	return true;
});
```
