### ISSUE TITLE
Error when viewing generated OpenAPI HTML file in browser

### ISSUE THREAD

**Issue by veerap000** [moon0326/wp-openapi#45]
I am using the WP CLI command to generate a single HTML file from OpenAPI with the following command:
wp openapi export --namespace=all --save_to=./export.html

The export.html file is successfully generated. However, when I try to view it in a browser (e.g., _myexamplesitedomain.test/export.html)_, I encounter a blank white page. The browser console shows the following error:
`Syntax error Uncaught SyntaxError: Unexpected token ':' (at export.html:10:1689396)`

The error seems to reference the following part of the code:
`entity:[{pattern:/&[\da-z]{1,8};/i `...

Is this a known issue or are there any workarounds to resolve this error?

**Comment by moon0326** [comment]
@veerap000 Thanks for the report.

That's not expected. Is it possible for you to upload the HTML so I can reproduce the error on my end?

**Comment by veerap000** [comment]
So we investigated this further @moon0326 and suspect that issue might be related to a character encoding in the `elements-js-js-after` inline script ([web-components.min.js](https://github.com/moon0326/wp-openapi/blob/main/resources/elements/web-components.min.js)).

The issue can be resolved by replacing the problematic inline script in the export.html file with the corresponding script from a file that works (that is created from Local).

When comparing the two scripts using DIFFchecker, some differences are detected:

[Minified files comparison](https://www.diffchecker.com/u7ho6gKQ/)
[Formatted comparison (split into rows)](https://www.diffchecker.com/0JnM7aqU/)
Left = code from export.html that has issue
Right = code from working export.html

Any ideas on what could be causing these discrepancies?

**Comment by moon0326** [comment]
@veerap000 Thanks for looking into it further. I'll look into it very soon.

**Comment by veerap000** [comment]
Thank you for pointing me in the right direction — That worked like a charm @moon0326!
