### ISSUE TITLE
Deprecated function: print_inline_script

### ISSUE THREAD

**Issue by veerap000** [moon0326/wp-openapi#53]
Getting deprecation warning when exporting a OpenAPI HTML with WP Cli.

`Deprecated: Function WP_Scripts::print_inline_script is deprecated since version 6.3.0! Use WP_Scripts::get_inline_script_data() or WP_Scripts::get_inline_script_tag() instead.`

used in: https://github.com/moon0326/wp-openapi/blob/1b7d38d1192938d32b5e85ad339b0ed3a095e161/resources/views/export-html.php#L10

**Comment by moon0326** [comment]
Thank you @veerap000. I'll look into it soon.

**Comment by moon0326** [comment]
Hi @veerap000 I've released version 1.0.16 to address this issue.

I'm closing this issue for now, but please feel free to re-open if needed.
