### ISSUE TITLE
`wp-openapi-filter-operations` doesn't fire

### ISSUE THREAD

**Issue by cawa-93** [moon0326/wp-openapi#59]
Seems `wp-openapi-filter-operations` doesn't fire at all.

I tried
```php
add_filter('wp-openapi-filter-operations', function() { exit; });
```
But nothing happened.

**Comment by moon0326** [comment]
Sorry about that @cawa-93 

I'll work on a fix.

Try `wp-openapi-filter-paths` instead in the meantime.

You can get operations with `getOperations` function. 

You can see an example here https://github.com/moon0326/wp-openapi/blob/main/src/Filters/AddCallbackInfoToDescription.php#L19
