### ISSUE TITLE
The `Operation` can't handle multiple security schemes or extra parameters

### ISSUE THREAD

**Issue by cawa-93** [moon0326/wp-openapi#60]
In current implementation `Operation` can accept only security scheme names

https://github.com/moon0326/wp-openapi/blob/6626d7c4986ad4d78b8ee42dec2c35442a67952d/src/Spec/Operation.php#L137-L144

- Not possible set any parameters like scopes for security, like [for OAuth 2.0](https://swagger.io/docs/specification/v3_0/authentication/oauth2/).
- Not possible to describe requirement to satisfy multiple schemes, like [Multiple API Keys](https://swagger.io/docs/specification/v3_0/authentication/api-keys/).

**Comment by moon0326** [comment]
@cawa-93 Version 1.0.17 has been released, addressing this issue along with others you’ve reported. Thank you for submitting them! 🙇
